# Generated by Django 4.0.2 on 2022-02-03 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('fileserver', '0001_initial'), ('fileserver', '0002_alter_file_filename_alter_file_sha_and_more'), ('fileserver', '0003_rename_file_id_idbinding_file_and_more'), ('fileserver', '0004_remove_file_ext_remove_file_filename_and_more'), ('fileserver', '0005_alter_file_file'), ('fileserver', '0006_file_filename'), ('fileserver', '0007_rename_url_url_redirect_url_idbinding_owner_and_more'), ('fileserver', '0008_alter_file_file'), ('fileserver', '0009_alter_file_file')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload')),
                ('filename', models.TextField(default='unknown')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IdBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(max_length=10)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileserver.file')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileserver.url')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
