# Generated by Django 4.0.2 on 2022-02-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=30)),
                ('ext', models.CharField(max_length=30)),
                ('mime_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IdBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(max_length=10)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileserver.file')),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileserver.url')),
            ],
        ),
    ]
