# Generated by Django 4.0.2 on 2022-02-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0002_alter_file_filename_alter_file_sha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idbinding',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='idbinding',
            old_name='url_id',
            new_name='url',
        ),
    ]
