# Generated by Django 4.0.2 on 2022-02-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0003_rename_file_id_idbinding_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ext',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='file',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='sha',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
