# Generated by Django 4.0.2 on 2022-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0007_rename_url_url_redirect_url_idbinding_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
