# Generated by Django 4.0.2 on 2022-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0008_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
    ]
